# Generated by Django 2.0.7 on 2018-08-03 07:37

import api.keygen
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteKeeperDeviceHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuscode', models.CharField(default='0000', max_length=250)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteKeeperDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', max_length=250)),
                ('deviceid', models.CharField(default=api.keygen.deviceID, max_length=25, unique=True)),
                ('ipDeviceName', models.CharField(default='eth0', max_length=64)),
                ('ipAddress', models.GenericIPAddressField(default='0.0.0.0')),
                ('ipMask', models.GenericIPAddressField(default='0.0.0.0')),
                ('ipGateway', models.GenericIPAddressField(default='0.0.0.0')),
                ('ipExternalAddress', models.GenericIPAddressField(default='0.0.0.0')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, to_field='userkey')),
            ],
        ),
        migrations.AddField(
            model_name='routekeeperdevicehistorymodel',
            name='deviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routekeeper.RouteKeeperDeviceModel', to_field='deviceid'),
        ),
    ]
