# Generated by Django 2.0.7 on 2018-08-09 04:15

import api.keygen
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteKeeperDeviceHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuscode', models.CharField(default='0000', max_length=250)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteKeeperDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', help_text='Name of the device (ex. RouteKeeper at House.)', max_length=250)),
                ('deviceid', models.CharField(default=api.keygen.deviceID, help_text='DeviceKEY for the device', max_length=25, unique=True)),
                ('ipDeviceName', models.CharField(default='eth0', help_text='Name of the device interface (ex. wlan0, en0, eth0, etc)', max_length=64)),
                ('ipAddress', models.GenericIPAddressField(default='0.0.0.0', help_text='IP Address of the device interface (ex. 192.168.1.2)')),
                ('ipMask', models.GenericIPAddressField(default='0.0.0.0', help_text='Subnet Mask Address of the device interface (ex. 255.255.255.0)')),
                ('ipGateway', models.GenericIPAddressField(default='0.0.0.0', help_text='Default Gateway Address of the device interface (ex. 192.168.1.1)')),
                ('ipExternalAddress', models.GenericIPAddressField(default='0.0.0.0', help_text='External Address of the device interface (ex. 64.181.10.22)')),
                ('owner', models.ForeignKey(help_text='Userkey of the device owner (ex. g215c-q955g)', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, to_field='userkey')),
            ],
        ),
        migrations.AddField(
            model_name='routekeeperdevicehistorymodel',
            name='deviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routekeeper.RouteKeeperDeviceModel', to_field='deviceid'),
        ),
    ]
