# Generated by Django 2.0.7 on 2018-08-03 14:53

import api.keygen
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routekeeperdevicemodel',
            name='deviceid',
            field=models.CharField(default=api.keygen.deviceID, help_text='DeviceKEY for the device', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='routekeeperdevicemodel',
            name='ipAddress',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='IP Address of the device interface (ex. 192.168.1.2)'),
        ),
        migrations.AlterField(
            model_name='routekeeperdevicemodel',
            name='ipDeviceName',
            field=models.CharField(default='eth0', help_text='Name of the device interface (ex. wlan0, en0, eth0, etc)', max_length=64),
        ),
        migrations.AlterField(
            model_name='routekeeperdevicemodel',
            name='ipExternalAddress',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='External Address of the device interface (ex. 64.181.10.22)'),
        ),
        migrations.AlterField(
            model_name='routekeeperdevicemodel',
            name='ipGateway',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='Default Gateway Address of the device interface (ex. 192.168.1.1)'),
        ),
        migrations.AlterField(
            model_name='routekeeperdevicemodel',
            name='ipMask',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='Subnet Mask Address of the device interface (ex. 255.255.255.0)'),
        ),
        migrations.AlterField(
            model_name='routekeeperdevicemodel',
            name='name',
            field=models.CharField(default='.', help_text='Name of the device (ex. RouteKeeper at House.)', max_length=250),
        ),
        migrations.AlterField(
            model_name='routekeeperdevicemodel',
            name='owner',
            field=models.ForeignKey(help_text='Userkey of the device owner (ex. g215c-q955g)', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, to_field='userkey'),
        ),
    ]
