# Generated by Django 2.0.7 on 2018-08-09 04:15

import api.keygen
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IOTChannelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', max_length=250)),
                ('channelid', models.CharField(default=api.keygen.channelID, max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOTCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', max_length=150)),
                ('customerid', models.CharField(default=api.keygen.getRandomID, max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOTSensorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorid', models.CharField(default=api.keygen.sensorID, max_length=30, unique=True)),
                ('name', models.CharField(default='Not Supplied', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(default='Undefined', max_length=250)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='iot.IOTChannelModel', to_field='channelid')),
            ],
        ),
        migrations.CreateModel(
            name='IOTSensorReadingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readingid', models.CharField(default=api.keygen.dataID, max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(default='Not Supplied', max_length=250)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='iot.IOTSensorModel', to_field='sensorid')),
            ],
        ),
        migrations.CreateModel(
            name='IOTTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', max_length=150)),
                ('tenantid', models.CharField(default=api.keygen.getRandomID, max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TenantOwner', to=settings.AUTH_USER_MODEL, to_field='userkey')),
            ],
        ),
        migrations.AddField(
            model_name='iotcustomer',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TenantOwner', to='iot.IOTTenant', to_field='tenantid'),
        ),
        migrations.AddField(
            model_name='iotchannelmodel',
            name='channelowner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channelowner', to='iot.IOTCustomer', to_field='customerid'),
        ),
    ]
