# Generated by Django 2.0.7 on 2018-08-09 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotchannelmodel',
            name='channelowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelowner', to='iot.IOTCustomer', to_field='customerid'),
        ),
    ]
