# Generated by Django 2.0.7 on 2018-08-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotsensorreadingmodel',
            name='readingid',
        ),
    ]
