# Generated by Django 2.0.7 on 2018-08-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20180808_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotsensormodel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='iot.IOTChannelModel', to_field='channelid'),
        ),
    ]
