# Generated by Django 2.0.7 on 2018-08-03 05:19

import api.keygen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_iotsensorreadingmodel_readingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotsensorreadingmodel',
            name='readingid',
            field=models.CharField(default=api.keygen.dataID, max_length=30, unique=True),
        ),
    ]
