# Generated by Django 2.0.7 on 2018-08-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20180803_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotchannelmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='iotsensormodel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='iotsensorreadingmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
