# Generated by Django 2.0.7 on 2018-08-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20180808_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotcustomer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TenantOwner', to='iot.IOTTenant', to_field='tenantid'),
        ),
    ]
