# Generated by Django 2.0.7 on 2018-08-03 07:37

import api.keygen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routekeeperdevicehistorymodel',
            name='deviceid',
        ),
        migrations.RemoveField(
            model_name='routekeeperdevicemodel',
            name='owner',
        ),
        migrations.AlterField(
            model_name='profile',
            name='userkey',
            field=models.CharField(default=api.keygen.userKEY, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='RouteKeeperDeviceHistoryModel',
        ),
        migrations.DeleteModel(
            name='RouteKeeperDeviceModel',
        ),
    ]
