# Generated by Django 2.0.7 on 2018-07-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteKeeperDeviceHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuscode', models.CharField(default='0000', max_length=250)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RouteKeeperDeviceModel')),
            ],
        ),
    ]
