# Generated by Django 2.0.7 on 2018-07-27 00:27

import api.keygen
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180726_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOTChannelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', max_length=250)),
                ('channelid', models.CharField(default=api.keygen.channelID, max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('channelowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelowner', to=settings.AUTH_USER_MODEL, to_field='userkey')),
            ],
        ),
        migrations.CreateModel(
            name='IOTSensorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorid', models.CharField(default=api.keygen.sensorID, max_length=30, unique=True)),
                ('name', models.CharField(default='Not Supplied', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='api.IOTChannelModel', to_field='channelid')),
            ],
        ),
        migrations.CreateModel(
            name='IOTSensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(default='Not Supplied', max_length=250)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='api.IOTSensorModel', to_field='sensorid')),
            ],
        ),
    ]
