# Generated by Django 2.0.7 on 2018-07-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_iotchannelmodel_iotsensormodel_iotsensorreading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IOTSensorReading',
            new_name='IOTSensorReadingModel',
        ),
    ]
