# Generated by Django 2.0.7 on 2018-07-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180726_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotchannelmodel',
            name='channelowner',
        ),
        migrations.RemoveField(
            model_name='iotsensormodel',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='iotsensorreadingmodel',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='IOTChannelModel',
        ),
        migrations.DeleteModel(
            name='IOTSensorModel',
        ),
        migrations.DeleteModel(
            name='IOTSensorReadingModel',
        ),
    ]
